### ISSUE TITLE
Java error after updating to version 1.0.49 from 1.0.48

### ISSUE THREAD

**Issue by GZLiew** [razorRun/react-native-vlc-media-player#145]
I just updated this library on my project but it cause the following error that crashed my app

I check the changes made on 1.0.49 but couldnt find what was causing this

```
03-20 14:05:20.968 10128 10128 W System.err: java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.facebook.react.bridge.ReadableMap.hasKey(java.lang.String)' on a null object reference
03-20 14:05:20.968 10128 10128 W System.err: 	at com.yuanzhou.vlc.vlcplayer.ReactVlcPlayerView.createPlayer(ReactVlcPlayerView.java:335)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.yuanzhou.vlc.vlcplayer.ReactVlcPlayerView.onSurfaceTextureAvailable(ReactVlcPlayerView.java:626)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.TextureView.getTextureLayer(TextureView.java:404)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.TextureView.draw(TextureView.java:353)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22767)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23901)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22767)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.drawChild(ReactViewGroup.java:836)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.views.view.ReactViewGroup.dispatchDraw(ReactViewGroup.java:809)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.facebook.react.ReactRootView.dispatchDraw(ReactRootView.java:296)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22753)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23628)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.drawChild(ViewGroup.java:5355)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java:5112)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.draw(View.java:23901)
03-20 14:05:20.968 10128 10128 W System.err: 	at com.android.internal.policy.DecorView.draw(DecorView.java:1378)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.View.updateDisplayListIfDirty(View.java:22767)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:602)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:608)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:684)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5445)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5153)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4217)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2924)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10513)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1108)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.Choreographer.doCallbacks(Choreographer.java:866)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.Choreographer.doFrame(Choreographer.java:797)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1092)
03-20 14:05:20.968 10128 10128 W System.err: 	at android.os.Handler.handleCallback(Handler.java:938)
03-20 14:05:20.969 10128 10128 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
03-20 14:05:20.969 10128 10128 W System.err: 	at android.os.Looper.loopOnce(Looper.java:226)
03-20 14:05:20.969 10128 10128 W System.err: 	at android.os.Looper.loop(Looper.java:313)
03-20 14:05:20.969 10128 10128 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8751)
03-20 14:05:20.969 10128 10128 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
03-20 14:05:20.969 10128 10128 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
03-20 14:05:20.969 10128 10128 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
03-20 14:05:20.970  1240  1270 I WindowManager: Reparenting to original parent: Surface(name=Task=271)/@0xce5df96, destroy=true, surface=Surface(name=Dim Layer for - Task=271 - animating-dim)/@0x8aca4af
03-20 14:05:20.970   879   879 I Layer   : FL_V_info: (BufferStateLayer)Name=23a38 xyz.tapendium.dev.videos/com.tapstream.MainActivity, Visible=1(Hiddenflag = 0, Alpha = 1.000000, [BufferInfo.mBuffer || mSidebandStream] = 2),Layer.flag=0x102
03-20 14:05:20.971  1608  2409 I ViewRootImpl@f4fd32f[videos]: mWNT: t = android.view.SurfaceControl$Transaction@a6fbfe6 fN = 3 android.view.SyncRtSurfaceTransactionApplier.applyTransaction:94 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0$SyncRtSurfaceTransactionApplier:71 android.view.SyncRtSurfaceTransactionApplier$$ExternalSyntheticLambda0.onFrameDraw:4 
03-20 14:05:20.971  1608  2409 I ViewRootImpl@f4fd32f[videos]: mWNT: merge t to BBQ
03-20 14:05:20.977   833  2560 I gralloc4: allocate: id=34100000d10, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC|BACKBUF, size=1200x1920, stride=1200, name=ViewRootImpl@8317654[MainActivity]#0(BLAST Consumer)0
03-20 14:05:20.979   833   833 I gralloc4: allocate: id=34100000d11, hal_format=RGBA8888, mali_format=RGBA8888, afbc=SPLIT, usage=GPU_RW|HWC|BACKBUF, size=1200x1920, stride=1200, name=ViewRootImpl@f4fd32f[videos]#76(BLAST Consumer)76
03-20 14:05:20.987   879   879 I Layer   : FL_V_info: (BufferStateLayer)Name=23a38 xyz.tapendium.dev.videos/com.tapstream.MainActivity, Visible=1(Hiddenflag = 0, Alpha = 1.000000, [BufferInfo.mBuffer || mSidebandStream] = 2),Layer.flag=0x102
03-20 14:05:20.987  1608  2410 I ViewRootImpl@f4fd32f[videos]: mWNT: t = android.view.SurfaceControl$Transaction@ff0f927 fN = 4 android.view.SyncRtSurfaceTransactionApplier.applyTransaction:94 android.view.SyncRtSurfaceTransactionApplier.lambda$scheduleApply$0$SyncRtSurfaceTransactionApplier:71 android.view.SyncRtSurfaceTransactionApplier$$ExternalSyntheticLambda0.onFrameDraw:4 
03-20 14:05:20.987  1608  2410 I ViewRootImpl@f4fd32f[videos]: mWNT: merge t to BBQ
03-20 14:05:20.989 10128 10128 E VLC/LibVLC: Can't load vlcjni library: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__sfp_handle_exceptions" referenced by "/data/app/~~Ye2W3EVKpyAPxGx_Klw8Hg==/xyz.tapendium.dev.videos-SZFsn_twRyKoRyDz8B07Dw==/lib/arm64/libvlc.so"...
03-20 14:05:20.990 10128 10128 I dium.dev.video: System.exit called, status: 1
03-20 14:05:20.990 10128 10128 I AndroidRuntime: VM exiting with result code 1, cleanup skipped.
03-20 14:05:21.003   879   879 I Layer   : id=2394 removedFromDrawingState Surface(name=Dim Layer for - Task=271 - animating-dim)/@0x8aca4af - animation-leash of dimmer#0 (133)
03-20 14:05:21.003   879   879 I SurfaceFlinger: id=2394 Removed Surface(name=Dim Layer for - Task=271 - animating-dim)/@0x8aca4af - animation-leash of dimmer#0 (133)
03-20 14:05:21.004  1608  1801 D OpenGLRenderer: setSurface called with nullptr
03-20 14:05:21.004  1608  1801 D OpenGLRenderer: setSurface() destroyed EGLSurface
03-20 14:05:21.004  1608  1801 D OpenGLRenderer: destroyEglSurface
03-20 14:05:21.004   879   879 I Layer   : id=2394 Destroyed Surface(name=Dim Layer for - Task=271 - animating-dim)/@0x8aca4af - animation-leash of dimmer#0
03-20 14:05:21.004   879   879 I Layer   : FL_V_info: (BufferStateLayer)Name=23a38 xyz.tapendium.dev.videos/com.tapstream.MainActivity, Visible=1(Hiddenflag = 0, Alpha = 1.000000, [BufferInfo.mBuffer || mSidebandStream] = 2),Layer.flag=0x102
03-20 14:05:21.005  1240  4843 V WindowManager: Relayout Window{ae15fd5 u0 Splash Screen xyz.tapendium.dev.videos}: viewVisibility=8 req=1920x1200 d0
03-20 14:05:21.006  1240  4843 I WindowManager: Reparenting to leash, surface=Surface(name=ae15fd5 Splash Screen xyz.tapendium.dev.videos)/@0x94a168, leashParent=Surface(name=ActivityRecord{5d39a60 u0 xyz.tapendium.dev.videos/com.tapstream.MainActivity t293})/@0x390ea49
03-20 14:05:21.006   879  2596 I SurfaceFlinger: id=2404 createSurf (0x0),-1 flag=24000, Surface(name=ae15fd5 Splash Screen xyz.tapendium.dev.videos)/@0x94a168 - animation-leash of window_animation#0
03-20 14:05:21.007  1240  4843 D WindowManager: makeSurface duration=1 leash=Surface(name=Surface(name=ae15fd5 Splash Screen xyz.tapendium.dev.videos)/@0x94a168 - animation-leash of window_animation)/@0x6e69981
03-20 14:05:21.009  1240  4843 V WindowManager: Relayout hash=ae15fd5, pid=1608: mAttrs={(0,0)(fillxfill) sim={adjust=pan} ty=APPLICATION_STARTING fmt=TRANSLUCENT wanim=0x1030303
03-20 14:05:21.009  1240  4843 V WindowManager:   fl=81030118
03-20 14:05:21.009  1240  4843 V WindowManager:   pfl=36000010
03-20 14:05:21.009  1240  4843 V WindowManager:   bhv=DEFAULT
03-20 14:05:21.009  1240  4843 V WindowManager:   fitSides= naviIconColor=0}
03-20 14:05:21.010  1608  1762 I ViewRootImpl@f4fd32f[videos]: Relayout returned: old=(0,0,1920,1200) new=(0,0,1920,1200) req=(1920,1200)8 dur=5 res=0x5 s={false 0} ch=true fn=5
03-20 14:05:21.011  1608  1762 I ViewRootImpl@f4fd32f[videos]: dispatchDetachedFromWindow
03-20 14:05:21.011  1240  4843 I WindowManager: Cancelling animation restarting=false, leash=Surface(name=Surface(name=23a38 xyz.tapendium.dev.videos/com.tapstream.MainActivity)/@0x8761850 - animation-leash of starting_reveal)/@0x98c2f4e
03-20 14:05:21.011  1240  4843 I WindowManager: Reparenting to original parent: Surface(name=ActivityRecord{5d39a60 u0 xyz.tapendium.dev.videos/com.tapstream.MainActivity t293})/@0x390ea49, destroy=false, surface=Surface(name=23a38 xyz.tapendium.dev.videos/com.tapstream.MainActivity)/@0x8761850
03-20 14:05:21.011  1240  4843 D InputTransport: Input channel destroyed: 'ae15fd5', fd=497
03-20 14:05:21.011  1240  4843 W InputManager-JNI: Input channel object 'ae15fd5 Splash Screen xyz.tapendium.dev.videos (client)' was disposed without first being removed with the input manager!
03-20 14:05:21.011  1240  4843 D InputTransport: Input channel destroyed: 'ae15fd5', fd=498
03-20 14:05:21.013  1608  1762 D InputTransport: Input channel destroyed: 'ae15fd5', fd=147

```

Downgrading back to 1.0.48 fixes the issue for me

"react": "18.2.0",
"react-native": "0.71.4",

**Comment by saad277** [comment]
@GZLiew same issue here

**Comment by GZLiew** [comment]
reference fix I found

https://github.com/razorRun/react-native-vlc-media-player/issues/101#issuecomment-1480953512
