### ISSUE TITLE
App crashes when playing RTSP streams

### ISSUE THREAD

**Issue by Yared-betsega** [razorRun/react-native-vlc-media-player#220]
When playing rtsp streams, the app crashes saying the app isn't responding [Close app, wait] error of Android system UI. 
I have 
RN version 0.76.1
"react-native-video": "^6.7.0",
"react-native-vlc-media-player": "^1.0.70",

**Comment by Yared-betsega** [comment]
Okay, it stopped crashing when I disabled bridgeless mode. However, I am not sure if it's a good idea to do so. Is there another way to fix it in the long term?

**Comment by DaveMcMartin** [comment]
I having the same problem, in my case I have an expo project v51, if I add this plugin the app crashes on Android but it works on iOS.

The log from the crash is

```bash
1-04 10:06:34.167 15707 15754 E AndroidRuntime: FATAL EXCEPTION: create_react_context
11-04 10:06:34.167 15707 15754 E AndroidRuntime: Process: com.neomot.annamobile, PID: 15707
11-04 10:06:34.167 15707 15754 E AndroidRuntime: com.facebook.soloader.SoLoaderDSONotFoundError: couldn't find DSO to load: libfolly_runtime.so
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	existing SO sources: 
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 		SoSource 0: ApplicationSoSource[DirectorySoSource[root = /data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/lib/arm64 flags = 0]]
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 		SoSource 1: DirectApkSoSource[root = [/data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/base.apk!/lib/arm64-v8a]]
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 		SoSource 2: DirectorySoSource[root = /system/lib64 flags = 2]
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 		SoSource 3: DirectorySoSource[root = /vendor/lib64 flags = 2]
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	Native lib dir: /data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/lib/arm64
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1096)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadDependency(SoLoader.java:856)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.DirectApkSoSource.loadDependencies(DirectApkSoSource.java:166)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:76)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1090)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadDependency(SoLoader.java:856)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.DirectApkSoSource.loadDependencies(DirectApkSoSource.java:166)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:76)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1090)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:869)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:808)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:774)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:39)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1102)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(Unknown Source:0)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(Unknown Source:4)
11-04 10:06:34.167 15707 15754 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
11-04 10:06:34.171 15707 15754 E DevLauncher: DevLauncher tries to handle uncaught exception.
11-04 10:06:34.171 15707 15754 E DevLauncher: com.facebook.soloader.SoLoaderDSONotFoundError: couldn't find DSO to load: libfolly_runtime.so
11-04 10:06:34.171 15707 15754 E DevLauncher: 	existing SO sources: 
11-04 10:06:34.171 15707 15754 E DevLauncher: 		SoSource 0: ApplicationSoSource[DirectorySoSource[root = /data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/lib/arm64 flags = 0]]
11-04 10:06:34.171 15707 15754 E DevLauncher: 		SoSource 1: DirectApkSoSource[root = [/data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/base.apk!/lib/arm64-v8a]]
11-04 10:06:34.171 15707 15754 E DevLauncher: 		SoSource 2: DirectorySoSource[root = /system/lib64 flags = 2]
11-04 10:06:34.171 15707 15754 E DevLauncher: 		SoSource 3: DirectorySoSource[root = /vendor/lib64 flags = 2]
11-04 10:06:34.171 15707 15754 E DevLauncher: 	Native lib dir: /data/app/~~pqBJwFNKLvA25EL7qyI0AQ==/com.neomot.annamobile-RV1mJCOenW5mm0fUHFanlw==/lib/arm64
11-04 10:06:34.171 15707 15754 E DevLauncher: 
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1096)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadDependency(SoLoader.java:856)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.DirectApkSoSource.loadDependencies(DirectApkSoSource.java:166)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:76)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1090)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadDependency(SoLoader.java:856)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.DirectApkSoSource.loadDependencies(DirectApkSoSource.java:166)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.DirectApkSoSource.loadLibrary(DirectApkSoSource.java:76)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:1090)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibraryBySoNameImpl(SoLoader.java:973)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:869)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:808)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:774)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.hermes.reactexecutor.HermesExecutor.loadLibrary(HermesExecutor.java:26)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.hermes.reactexecutor.HermesExecutor.<clinit>(HermesExecutor.java:20)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.hermes.reactexecutor.HermesExecutorFactory.create(HermesExecutorFactory.java:39)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2(ReactInstanceManager.java:1102)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.react.ReactInstanceManager.$r8$lambda$AwGS8CysOZmWJw3kRVARHQvw9Ew(Unknown Source:0)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at com.facebook.react.ReactInstanceManager$$ExternalSyntheticLambda5.run(Unknown Source:4)
11-04 10:06:34.171 15707 15754 E DevLauncher: 	at java.lang.Thread.run(Thread.java:1012)
11-04 10:06:34.496   573   752 E WindowManager: setOnBackInvokedCallback(): No window state for package:com.android.systemui
11-04 10:07:00.109  1038  1038 E BcSmartspaceCard: No tap action can be set up
```

![Screenshot 2024-11-04 at 10 06 47](https://github.com/user-attachments/assets/9cf87c1d-747f-4be4-aff3-e59a6e5db07f)

I could open a PR to fix this if I knew how to do it.
